Repository nhcarrigan/becca-lyria, pull requests merged in 2020-09, with the labels that each got.

#121 Restructure
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/labeler.yml
  .github/workflows/dependabot.yml
  .github/workflows/greetings.yml
  .github/workflows/labeler.yml
  .github/workflows/merge-conflict.yml
  .github/workflows/stale.yml
Labels: status: approved, type: chore

#122 Fix issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: status: awaiting review

#127 Replace Travis with a GH Action
  .github/workflows/node-ci.yml
  .travis.yml
Labels: status: approved

#129 Update to linter
  package-lock.json
  package.json
Labels: status: approved

#130 Revise docs
  CONTRIBUTING.md
  README.md
Labels: status: approved

#133 Chore/replace messages
  README.md
  package.json
  src/commands/about.ts
  src/commands/ban.ts
  src/commands/cat.ts
  src/commands/close.ts
  src/commands/compliment.ts
  src/commands/dndclass.ts
  src/commands/dndmon.ts
  src/commands/dndrace.ts
  src/commands/dndschool.ts
  src/commands/dndspell.ts
  src/commands/fortune.ts
  src/commands/github.ts
  src/commands/guess.ts
  src/commands/habitica.ts
  src/commands/help.ts
  src/commands/hpchar.ts
  src/commands/hpsort.ts
  src/commands/hpspell.ts
  src/commands/http.ts
  src/commands/jobs.ts
  src/commands/joke.ts
  src/commands/kick.ts
  src/commands/kirby.ts
  src/commands/leave.ts
  src/commands/levels.ts
  src/commands/listen.ts
  src/commands/magic.ts
  src/commands/maths.ts
  src/commands/motivate.ts
  src/commands/ping.ts
  src/commands/pokename.ts
  src/commands/pokenum.ts
  src/commands/profile.ts
  src/commands/purge.ts
  src/commands/restrict.ts
  src/commands/roll.ts
  src/commands/server.ts
  src/commands/space.ts
  src/commands/star.ts
  src/commands/trivia.ts
  src/commands/unrestrict.ts
  src/commands/uptime.ts
  src/commands/usage.ts
  src/commands/user.ts
  src/commands/warn.ts
  src/commands/wiki.ts
  src/commands/xkcd.ts
  src/listeners/levelsListen.ts
  src/main.ts
Labels: status: approved

#134 Add privacy policy and command
  PRIVACY.md
  package.json
  src/COMMANDS.ts
  src/commands/privacy.ts
  src/commands/user.ts
  src/main.ts
Labels: status: approved

#136 Add message edit listener
  package.json
  src/main.ts
Labels: status: approved, status: awaiting review

#137 Add response delay, typing feature
  package.json
  src/main.ts
Labels: status: approved

#143 V 4.16.0 - add config command
  package.json
  src/COMMANDS.ts
  src/commands/config.ts
Labels: status: approved

#171 Feat/riddles
  package.json
  src/COMMANDS.ts
  src/commands/riddle.ts
  src/interfaces/RiddleInt.ts
Labels: status: approved

#172 [REQUEST] - Title Command
  package.json
  src/COMMANDS.ts
  src/commands/title.ts
  src/interfaces/WordInt.ts
Labels: status: approved

#173 Add challenge command
  package.json
  src/COMMANDS.ts
  src/commands/challenge.ts
  src/interfaces/ChallengeInt.ts
Labels: status: approved

#174 Add maze command
  package.json
  src/COMMANDS.ts
  src/commands/maze.ts
  src/interfaces/MazeInt.ts
Labels: status: approved

#175 Add adventure command
  package.json
  src/COMMANDS.ts
  src/commands/adventure.ts
  src/interfaces/AdventureInt.ts
Labels: status: approved

#177 Fix a few copy-paste errors
  package.json
  src/commands/challenge.ts
  src/commands/maze.ts
Labels: status: approved

#179 Fix #176 - Leaving guild changes mention
  src/main.ts
Labels: status: approved

#184 Removed Welcome DM
  src/main.ts
Labels: status: approved
